id: AB7F2EEEB
base_file: f2C0E.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:55:52.352080
  last_modified_at: 2022-05-30 18:55:52.352088
